name = "way2go-cloud"
main = "src/worker.ts"
compatibility_date = "2026-05-15"

[assets]
directory = "./dist"

[ai]
binding = "AI"

[[routes]]
pattern = "way2go.cloud/*"
zone_name = "way2go.cloud"

[[routes]]
pattern = "www.way2go.cloud/*"
zone_name = "way2go.cloud"
